package com.automate.df.enums;

public enum LeadStatus {
    PREENQUIRY,
    ENQUIRY,
    ENQUIRYCOMPLETED,
    PREBOOKING,
    CONTACTED,
    NOT_CONTACTED,
    DISBURSED,
    PREBOOKINGCOMPLETED,
    BOOKING,
    BOOKINGCOMPLETED,
    PREDELIVERY,
    PREDELIVERYCOMPLETED,
    DELIVERY,
    DELIVERYCOMPLETED,
    INVOICE,
    INVOICECOMPLETED,
    SENTFORAPPROVAL,
    REJECTED
}
