package com.automate.df.enums;

public enum WorkflowTaskCategory {

    SMS,
    EMAIL,
    PREENQUIRYFOLLOWUP,
    TESTDRIVE,
    APPROVAL,
    ENQUIRYFOLLOWUP,
    PREENQUIRY,
    HOMEVISIT,
    EVALUATION,
    FINANCE,
    DOCUMENTCOLLECTION,
    OFFERS,
    BOOKINGADVANCE,
    PAYMENT,
    INVOICE,
    DELIVERY,
    TESTDRIVEAPPROVAL,
    BOOKING,
    HOMEVISITAPPROVAL,
    EVALUATIONAPPROVAL,
    FINANCEAPPROVAL,
    PREBOOKING,
    ALLOTMENT


}
